# Generated by Django 5.0.1 on 2024-03-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blog_autor_alter_blog_cuerpo_alter_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(),
        ),
    ]
